/**
 * build-client.mjs — 把 src/client/* 与 src/vendor/grok-ball.engine.js 组装成
 * 单个 lib/client.js。
 *
 * dsh 的客户端插件每个包只提供一个浏览器 bundle（/plugins/<id>/client.js），
 * 因此这里把引擎注册成同一文件内的独立模块（各自一个 __ModuleLoader__.load
 * 注册），主工厂再用 require("<包名>/engine/grok-ball") 取到它。
 *
 * 用法：node build-client.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const PKG = '@dsh-local/dsh-client-ui-float-ball';
const VERSION = '0.1.0';

const read = (rel) => readFileSync(join(here, rel), 'utf8');
const pad = (n) => String(n).padStart(2, '0');

/* ---- 1) 引擎模块：包装成模块表里的一行 -------------------------------- */
const engineSrc = read('src/vendor/grok-ball.engine.js');
const engineModule =
  `window.__ModuleLoader__.load({\n` +
  `  id: ${JSON.stringify(PKG + '/engine/grok-ball')},\n` +
  `  factory: (require) => {\n` +
  `    var module = { exports: {} };\n` +
  `    var exports = module.exports;\n` +
  `/* ---- vendored from grok-ball (MIT, https://github.com/tycoding/grok-ball) ---- */\n` +
  engineSrc +
  `\n/* ---- end vendored engine ---- */\n` +
  `    module.exports = window.GrokBall || window.EmotionBall;\n` +
  `    return module.exports;\n` +
  `  }\n` +
  `});\n`;

/* ---- 2) 主模块：src/client/*.js 按文件名顺序拼接 ---------------------- */
const parts = ['10-util.js', '15-style.js', '18-speech.js', '22-pricing.js', '24-life.js', '20-ball.js', '25-brain.js', '30-panel.js', '90-main.js'];
const body = parts
  .map((file) => {
    const src = read(join('src/client', file));
    return `\n/* ==================== src/client/${file} ==================== */\n${src}`;
  })
  .join('\n');

/* 依赖注入：把同一工厂内的兄弟模块句柄交给 Util，源码里就不必再写
 * require() 路径字符串，也避免 Util 与各模块之间出现循环引用。 */
const wire =
  `\n/* ==================== build: 依赖接线 ==================== */\n` +
  `initUtil({ Engine: Engine, FloatBall: FloatBall, Panel: PanelContent });\n` +
  `module.exports.name = "dsh-client-ui-float-ball";\n` +
  `module.exports.NS = NS;\n` +
  `module.exports.apply = apply;\n` +
  `module.exports.inject = inject;\n` +
  `module.exports.version = ${JSON.stringify(VERSION)};\n` +
  `/* 构建机冒烟测试钩子（线上无副作用） */\n` +
  `module.exports.__antics = typeof startLifeLoop === "function" ? startLifeLoop : null;
  ` +
  `module.exports.__gazeVector = typeof gazeVector === "function" ? gazeVector : null;
  ` +
  `module.exports.__speech = typeof speechState === "function" ? { state: speechState, reset: resetSpeechThrottle, quality: speechQuality } : null;
  ` +
  `module.exports.__pricing = typeof pricingState === "function" ? { state: pricingState, tier: computePricingTier, announce: announcePricing } : null;\n` +
  `/* 调试钩子：仅用于构建机上的 jsdom 冒烟测试 */\n` +
  `window.__dshFloatBall = { panelState: typeof panelState !== "undefined" ? panelState : null, openPanel: typeof openPanel !== "undefined" ? openPanel : null, uiStore: uiStore, Engine: Engine };\n`;

const mainModule =
  `window.__ModuleLoader__.load({\n` +
  `  id: ${JSON.stringify(PKG)},\n` +
  `  factory: (require) => {\n` +
  `    var module = { exports: {} };\n` +
  `    var exports = module.exports;\n` +
  `    var react = require("react");\n` +
  `    var reactDom = require("react-dom");\n` +
  `    var jsxRuntime = require("react/jsx-runtime");\n` +
  `    var jsx = jsxRuntime.jsx;\n` +
  `    var jsxs = jsxRuntime.jsxs;\n` +
  `    var Fragment = jsxRuntime.Fragment;\n` +
  `    var Engine = require(${JSON.stringify(PKG + '/engine/grok-ball')});\n` +
  body +
  wire +
  `    return module.exports;\n` +
  `  }\n` +
  `});\n`;

const header =
  `/* Generated by build-client.mjs — do not edit directly.\n` +
  ` * 源文件：src/client/*.js + src/vendor/grok-ball.engine.js\n` +
  ` * 重新生成：node build-client.mjs\n` +
  ` */\n`;

const out = header + engineModule + mainModule;

mkdirSync(join(here, 'lib'), { recursive: true });
writeFileSync(join(here, 'lib/client.js'), out);
console.log(
  `lib/client.js written (${out.length} bytes, ${parts.length} source parts + 1 engine, build ${VERSION}, t=${pad(new Date().getMinutes())})`
);
